- id: 1a3a610758658ecb
  type: modbus-client
  name: SCARA-左
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 193.168.110.43
  tcpPort: '502'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: 1
  commandDelay: 1
  clientTimeout: 1000
  reconnectOnTimeout: true
  reconnectTimeout: 2000
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: ebdc7b3b4236640e
  type: modbus-client
  name: 虚拟modbus-40
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 127.0.0.1
  tcpPort: '10040'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showWarnings: true
  showLogs: true
- id: 1c6dae42783642fa
  type: modbus-client
  name: SCARA-右
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 193.168.110.44
  tcpPort: '502'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: 30dcaa59b1afd833
  type: modbus-client
  name: 泛在控制器-linux
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 193.168.110.40
  tcpPort: '503'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: 1
  commandDelay: 1
  clientTimeout: 1000
  reconnectOnTimeout: true
  reconnectTimeout: 2000
  parallelUnitIdsAllowed: true
  showWarnings: true
  showLogs: true
