- id: sqlitedb_id
  type: sqlitedb
  db: datas.db
  mode: RWC
- id: ext-controller
  type: modbus-client
  name: OP40-泛在控制器
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: localhost
  tcpPort: '503'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: scara-left
  type: modbus-client
  name: OP40-左scara
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: localhost
  tcpPort: '504'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: scara-right
  type: modbus-client
  name: OP40-右scara
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: localhost
  tcpPort: '505'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: virtual-modbus
  type: modbus-client
  name: OP40-虚拟modbus
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: localhost
  tcpPort: '506'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
