- id: f45c8577844ced46
  type: modbus-client
  name: 虚拟modbus-20
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 127.0.0.1
  tcpPort: '10020'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showWarnings: true
  showLogs: true
- id: b491bf7158494622
  type: modbus-client
  name: 泛在控制器-20
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 192.168.105.232
  tcpPort: '502'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: 1a3a610758658ecb
  type: modbus-client
  name: 6轴-OP30
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 192.168.110.30
  tcpPort: '502'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: ebdc7b3b4236640e
  type: modbus-client
  name: 虚拟modbus-30
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 127.0.0.1
  tcpPort: '10030'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
