- id: 9a4dd78996491658
  type: modbus-client
  name: screw-front
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 192.168.110.73
  tcpPort: '23'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: 6f8d38c417897cab
  type: modbus-client
  name: controller
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 192.168.105.232
  tcpPort: '502'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: 1
  commandDelay: 1
  clientTimeout: 1000
  reconnectOnTimeout: true
  reconnectTimeout: 2000
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: 7c8eaadd51bb903a
  type: modbus-client
  name: screw-back
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 192.168.110.74
  tcpPort: '23'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
- id: f45c8577844ced46
  type: modbus-client
  name: 虚拟modbus-70
  clienttype: tcp
  bufferCommands: true
  stateLogEnabled: false
  queueLogEnabled: false
  failureLogEnabled: true
  tcpHost: 127.0.0.1
  tcpPort: '10070'
  tcpType: DEFAULT
  serialPort: /dev/ttyUSB
  serialType: RTU-BUFFERD
  serialBaudrate: '9600'
  serialDatabits: '8'
  serialStopbits: '1'
  serialParity: none
  serialConnectionDelay: '100'
  serialAsciiResponseStartDelimiter: '0x3A'
  unit_id: '1'
  commandDelay: '1'
  clientTimeout: '1000'
  reconnectOnTimeout: true
  reconnectTimeout: '2000'
  parallelUnitIdsAllowed: true
  showErrors: false
  showWarnings: true
  showLogs: true
